"""estructura inicial

Revision ID: 4c5e8891bc67
Revises: 
Create Date: 2026-04-02 14:19:56.290246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5e8891bc67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('contraseña', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('duelos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_rival', sa.String(length=20), nullable=False),
    sa.Column('modo', sa.String(length=20), nullable=False),
    sa.Column('driver_number_1', sa.Integer(), nullable=False),
    sa.Column('piloto1', sa.String(length=100), nullable=False),
    sa.Column('driver_number_2', sa.Integer(), nullable=False),
    sa.Column('piloto2', sa.String(length=100), nullable=False),
    sa.Column('circuito_key', sa.Integer(), nullable=False),
    sa.Column('circuito', sa.String(length=100), nullable=False),
    sa.Column('ganador', sa.String(length=100), nullable=True),
    sa.Column('tiempo_1', sa.Float(), nullable=True),
    sa.Column('tiempo_2', sa.Float(), nullable=True),
    sa.Column('diferencia', sa.Float(), nullable=True),
    sa.Column('ganador_usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ganador_usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escuderias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('presupuesto_max', sa.Integer(), nullable=False),
    sa.Column('coste_total', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duelos_escuderia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_rival', sa.String(length=20), nullable=False),
    sa.Column('modo', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('circuito_key', sa.Integer(), nullable=False),
    sa.Column('circuito', sa.String(length=100), nullable=False),
    sa.Column('escuderia_usuario_id', sa.Integer(), nullable=False),
    sa.Column('escuderia_rival_id', sa.Integer(), nullable=False),
    sa.Column('escuderia_usuario_nombre', sa.String(length=100), nullable=False),
    sa.Column('escuderia_rival_nombre', sa.String(length=100), nullable=False),
    sa.Column('ganador', sa.String(length=100), nullable=True),
    sa.Column('tiempo_usuario', sa.Float(), nullable=True),
    sa.Column('tiempo_rival', sa.Float(), nullable=True),
    sa.Column('diferencia', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escuderia_rival_id'], ['escuderias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['escuderia_usuario_id'], ['escuderias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participar',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('duelo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['duelo_id'], ['duelos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'duelo_id')
    )
    op.create_table('pilotos_escuderia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('escuderia_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escuderia_id'], ['escuderias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pilotos_escuderia')
    op.drop_table('participar')
    op.drop_table('duelos_escuderia')
    op.drop_table('escuderias')
    op.drop_table('duelos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
